apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
        - name: web-server
          image: yuva19102003/golang-webserver:v8c57dd2092d96417d58ca49e12f3b3efec542913
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: API_KEY
              value: 'http://golangapi-service:8080'
         
---

apiVersion: v1
kind: Service
metadata:
  name: web-server-service
spec:
  selector:
    app: web-server
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
